### ISSUE TITLE
eslint not found

### ISSUE THREAD

**Issue by AshleyLerma** [J-A-M-M-S/gitLit#15]

**Comment by juanlajara** [comment]
`#!/bin/bash -eo pipefail
./cc-test-reporter before-build
npm test -- --coverage
./cc-test-reporter after-build --exit-code $?

> mern@1.0.0 test /home/circleci/project
> npm run lint && cross-env NODE_ENV=test mocha -u tdd --reporter spec --exit "--coverage"


> mern@1.0.0 lint /home/circleci/project
> eslint "**/*.js"

/home/circleci/project/node_modules/eslint/lib/cli-engine/cli-engine.js:256
        ...calculateStatsPerFile(messages)
        ^^^

SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/home/circleci/project/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/home/circleci/project/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/home/circleci/project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/circleci/project/node_modules/eslint/lib/cli-engine/index.js:3:23)
    at Module._compile (/home/circleci/project/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)

npm ERR! Linux 4.15.0-1077-aws
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mern@1.0.0 lint: `eslint "**/*.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mern@1.0.0 lint script 'eslint "**/*.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mern package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint "**/*.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mern
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mern
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/circleci/project/npm-debug.log
npm ERR! Test failed.  See above for more details.


Exited with code exit status 1
CircleCI received exit code 1`
